const Term5 = () => {
    return (
        <div>
            <h1>Тема 5</h1>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
            <p>da</p>
        </div>
    )
}

export default Term5;